name: Bug Report
description: Describe the bug you encountered to help us improve RSpace.
title: "[BUG]: "
labels: ["bug"]
assignees:
  - tilorspace
body:
  - type: markdown
    attributes:
      value: |
        ## Describe the bug 
        A clear and concise description of what the bug is. 
        **⚠️ Please make sure not to include sensitive or confidential information.**

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      
  - type: input
    id: rspace-version
    attributes:
      label: Which RSpace version did you encounter the bug with?
      placeholder: e.g. 1.101
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        
        ### What device, operating system and browser were you using when you encountered the bug?
      

  - type: dropdown
    id: device
    attributes:
      label: Mobile / Desktop / API
      options: 
        - Mobile
        - Desktop
        - API
    validations:
      required: true
      
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g. iOS
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: e.g. chrome, safari
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser version
      placeholder:
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
